---
title: "Active Brownian particles: from collective phenomona to fundamental physics"
author: "Gompper, Winkler"
date: 2023-10-04 15:04
---

## Concepts

- Janus particles
- Active Brownian particles (ABPs)
- Colloidal particles
- What's common to both propulsion mechanisms is that they are break detailed
balance (irreversible?) by receiving an input of free energy that eventually
gets dissipated into the environment.

## MIPS

- Motility-induced phase separation
- Self-propelled particles aggregate into clusters even in the absence of
cohensive forces.
  - The mechanism is dynamic feedback between speed and density
- Exploiting the directed motion of synthetic active particles to convert
chemical free energy (released by hydrogen peroxide) into mechanical work.

# Light-driven propulsion

- Using illumination patterns to guide particles towards target regions.
  - This is faster than passive diffusion.

- Using quorum sensing (members of population excreting signalling molecules to
create non-uniform concentration profile) in synthetic active particles to
achieve aggregation at low densities.

- Main interest is the emergent collective behaviour for a given model
  - But the **inverse** problem is also interesting: we can determine rules
  that lead to a desired target state.
  - In passive matter, this is done through coarse-graining.
  - In non-equilibrium active systems, this is mainly missing, but the
  deployment of machine learning concepts is predicted.
