---
title: "2020 Motile Active Matter Introduction"
author: "Gompper, Winkler"
date: 2023-10-04 15:04
---

## General principles and methods

Theories of active matter have to be constructed on the basis of symmetries,
conservation laws, and dynamic rules.

Methods involved simulations, field-theoretical methods, dynamic
density-functional theory.

## Micro/nano swimmers

Biological swimmers can employ cilia or flagella or changes in body shape to
propel to towards a target.

Additionally, another point of interest would be search strategies: like
**chemotaxis** (orientation/movement away or from stimulus, along a chemical
concentration gradien) and **photoaxis** (orientation/movement away or from
light).

- How small a swimmer can be to still display directed motion?

## Synthetic micro/nano machines

**Various strategies for autonomous machines**

Diffusiophoresis - motion of species A in response to the concentration
gradient of species B (both in a colloid)

Thermophoresis - motion in mixture of particles along temperature gradient.

An important model to study collective motion far from equilibrium: a mixtrue
of semiflexible polar filaments and motor proteins.

Active nematic theory (??) is fruitful in modelling many observed phenomena.

## Swarming

Interests in observing reaction of swarms to external signals.

  - Reaction of bird flocks to predators
  - Algae in gravitational field

Interests in light control of synthetic systems
