---
title: "Run-and-tumble dynamics in a crowded environment: PEP for swimmers"
author: "Soto, Golestanian"
date: 2023-09-29 21:30
---

## The model

The model is asynchronous and stochastic.

Particles in the **run** phase characterised by **direction**:

-   `(left,right)` in 1D
-   `(left,right,up,down)` in 2D

A total number of particles $M = \phi N$ where $\phi$ is the particle
concentration and $N$ is the total number of sites.

Each particle moves in a random direction, with probability $\alpha$ to undergo
**tumbling**.

If the neighbouring site that it's pointing towards (the value of the
**director**) is not fully occupied, it moves into this new position.

At each step, particles can be chosen more than once, and $M$ particles are
chosen on average.

Non-equilibrium feature (in the limit of infinite dilution): each particle
stays in **run** mode for periods of time that are geometrically distributed
with an average of $\alpha^{-1}$, then undergoes a **tumble**.

**Jamming** happens when two particles moving on the same track but in opposite
directions. This creates a **cluster seed**.

Effects at $\alpha = 0$

-   All particles become jammed.
-   Particles cluster together until there are no more isolated particles.

Effects at $\alpha \neq 0$

-   The system forms clusters that coexist.
-   The clusters stay immobile, so there is no merging or splitting.
-   There is now cluster dynamics with the following processes:
    1.  Formation of cluster by two particle colliding
    2.  Absorption of moving particles at cluster boundaries
    3.  Particle evaporation at the boundaries
