project:
  title: "Dissipation Learning in Active Matter"
  type: website

theme:
  light: [flatly, theme-light.scss]
  dark: [darkly, theme-dark.scss]

website:
  title: "Dissipation Learning in Active Matter"
  description: "MSci project 2023-24"
  repo-url: https://github.com/mstcl/msci-wiki
  repo-actions: [edit, issue, source]
  page-navigation: true
  repo-branch: np
  back-to-top-navigation: true
  search:
    location: sidebar
    type: textbox
  reader-mode: true
  page-footer:
    center:
      - text: "Made with Quarto"
        href: https://quarto.org
      - text: "License"
        href: https://creativecommons.org/licenses/by-nd/4.0/
    right:
      - text: "Version: NP"
  sidebar:
    alignment: center
    search: true
    style: "docked"
    contents:
      - text: "---"
      - section: "Main content"
        contents:
          - auto: activity_log/!(landing).*
          - auto: plots/!(landing).*
          - auto: training/!(landing).*
          - auto: literature_notes/!(landing).*md
          - auto: writings/!(landing).*
          - section: "FT notes"
            contents:
              - auto: shared/ftnotes/*
      - text: "---"
      - section: "Project information"
        contents:
          - text: "Deadlines"
            file: shared/deadlines.qmd
          - text: "Repository"
            file: shared/repo.qmd
          - text: "Cluster"
            file: shared/cluster.qmd
      - text: "---"
      - section: "External links"
        contents:
        - text: "Network logbook"
          icon: link-45deg
          href: "https://cryptpad.fr/sheet/#/3/sheet/edit/7200dabe21ea346d966571a07eb6f33a/"
        - text: "Zotero library"
          icon: link-45deg
          href: "https://www.zotero.org/groups/5210328/dissipation_learning_in_active_matter/library"
        - text: "GitHub mirror"
          icon: link-45deg
          href: "https://github.com/mstcl/msci-wiki"
      - text: "---"
      - text: "All pages"
        file: sitemap.qmd
    tools:
      - icon: git
        href: "https://github.com/dlactivematter"

format:
  html:
    toc: true
    toc-depth: 3
    code-line-numbers: true
    highlight-style: gruvbox
    toc-title: Content
    code-fold: false
    page-layout: article
    html-math-method: mathjax
    anchor-sections: true
    smooth-scroll: true
    code-tools:
      source: true
      toggle: true
      caption: none
    mainfont: sans-serif
    monofont: monospace
    # link-external-icon: true
    # link-external-newwindow: true
    # link-external-filter: '^(?:http:|https:)\/\/.mstcl\.github.io\/msci-wiki'
    # linkcolor: rgb(213,43,43)
jupyter: python3
