---
title: Week 4
date: 2023-10-13
author: NP
---

## Tasks

- [x] Act on feedback on [writing](../writings/motivation.qmd) from last week.
- [ ] We can aim to make a density map of snapshots ($\alpha / \phi$), on a 3x3 grid.
  - Range of $\alpha$: [0.01, 0.5], 10 values in total, split between me
    and CP.
  - Use scikit-learn to detect clusters and cluster size.
  - See [this notebook](../shared/ftnotes/label.ipynb) for a demo.
  - I didn't get enough time to do any cluster analysis, just the grid of snapshots.

## Summary

### General

- I acted on the feedback, which is reflected [here](../writings/motivation.qmd).
- We decided on a range $\alpha$, which is 10 values spaced logarithmically
  (base 2) in the range [2^-6^,2^-1^]. We thought this would be a sensible
  range for the snapshot grid, and we weren't sure whether to go with
  log-spacing or normal spacing. In the end, we went with log-spacing.
- For $\phi$ (density), we decided on a range of [0.05,0.5], with intervals of 0.05,
  giving a total of 10 values.
- We modified `sampler.py` to reflect this, and regenerated the data so that we
  get a set of static datasets to work on creating this grid, ensuring the plot
  can be reproduced. I ran everything on the cluster this time.

### Plotting snapshots

- I began making plots of a selection of these datasets (a 3x5 grid), first as
  individual plots to before I spend more time and place them all on one figure.
  Then, I put them altogether on one grid:

![The three values of $\phi$ here are (left to right) 0.05, 0.25 and 0.45 (all
in units^-2^). The five values of $\alpha$ here are (top to bottom) 0.023,
0.050, 0.107, 0.231, 0.500.](../assets/grid.png)

- I tried to add figure x and y labels but the matplotlib I was using was too old
  to support `fig.supxlabel` or `fig.supylabel`. I also need to add labels for each
  block to indicate the value $(\phi, \alpha)$.
